/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Sender = IDL.Variant({
  'user' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Time = IDL.Int;
export const Message = IDL.Record({
  'text' : IDL.Text,
  'sender' : Sender,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getAll' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getRange' : IDL.Func(
      [IDL.Opt(Time), IDL.Opt(Time)],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'send' : IDL.Func([IDL.Text, Sender], [Time], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Sender = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'text' : IDL.Text,
    'sender' : Sender,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getAll' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getRange' : IDL.Func(
        [IDL.Opt(Time), IDL.Opt(Time)],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'send' : IDL.Func([IDL.Text, Sender], [Time], []),
  });
};

export const init = ({ IDL }) => { return []; };